### ISSUE TITLE
Too many root sets (core dumped)

### ISSUE THREAD

**Issue by gvolpe** [nixbuild/nixbuild-action#30]
Hi @rickynils and co 👋🏽 ,

I am giving this action a try to build my Home Manager configuration, but I bumped into [this error](https://github.com/gvolpe/nix-config/actions/runs/4113602758/jobs/7099935867): 

```console
Too many root sets
/home/runner/work/_temp/df5ac549-c409-4a1f-bfad-35d26e301c9b.sh: line 8:  1847 Aborted                 (core dumped) nix build "./.#packages.x86_64-linux.home-hdmi" --print-build-logs --eval-store auto --store ssh-ng://eu.nixbuild.net --builders "" --max-jobs 2 --json > build.json 2> >(tee -a build.log >&2)
Error: Process completed with exit code 1.
```

On a second run, I got a [different error](https://github.com/gvolpe/nix-config/actions/runs/4113703021/jobs/7100160609):

```console
skypeforlinux> [nixbuild.net] Waiting 4 seconds for an ongoing build of /nix/store/8kpcm758a6fcn51ik8a65zhh2hxv31nx-skypeforlinux-8.87.0.406.drv
error: [nixbuild.net] '/nix/store/42ph7l1rwx738444jcrd5l4vya0xfigf-home-manager-generation.drv': dependency failed
       '/nix/store/i4nvpcnv7bnb9sx3c7hd934h0s8jnbba-activation-script.drv': dependency failed
       '/nix/store/76dwvgg6i9sax1y201qk4g1jyff3v05g-xmonad-compile.drv': dependency failed
       build cancelled
Error: Process completed with exit code 1.
```

Retring the failed jobs (2), gets me a [different error](https://github.com/gvolpe/nix-config/actions/runs/4113703021/jobs/7100850585):

```console
chatgpt_for_google> curl: (22) The requested URL returned error: 404
chatgpt_for_google> error: cannot download chatgpt_for_google-1.15.1.xpi from any mirror
chatgpt_for_google> [nixbuild.net] End of replayed build log
error: [nixbuild.net] '/nix/store/d4bjagdh8wiks4nnd3wqjzzqi8x4sar4-home-manager-generation.drv': dependency failed
       '/nix/store/iaxnfwl2llrjszbp5y65x77jsmc1ymrs-home-manager-files.drv': dependency failed
       '/nix/store/4jgi3njb141n0lmh2nsdw6kl3sbzb88i-hm-firefox-extensions.drv': dependency failed
       '/nix/store/525sjfcmp2p396594xs979nlyb8akwf1-chatgpt_for_google-1.15.1.drv': dependency failed
       '/nix/store/zwgz688ac3sijfc1rlqdk7dh4afhvrlb-chatgpt_for_google-1.15.1.xpi.drv': build failed: Cached build failure: builder for '/nix/store/zwgz688ac3sijfc1rlqdk7dh4afhvrlb-chatgpt_for_google-1.15.1.xpi.drv' failed with exit code 1
Error: Process completed with exit code 1.
```

Any ideas what's going wrong? This actually builds on CI and my machine, would appreciate any help. 

Here's my PR: https://github.com/gvolpe/nix-config/pull/163

---

Unrelated to this error, I got some further feedback:

- I had to use `master` because the latest version `v15` uses Nix 2.11.0, which doesn't seem to support IFD in the config. A proper release would be nice.
- It would be great if the [summary is produced](https://github.com/gvolpe/nix-config/actions/runs/4113703021) even if some jobs fail, as there are some resources being used that count towards the final bill.

**Comment by rickynils** [comment]
The `Too many root sets` issue is a client error that started to appear in Nix around version 2.11.1, see https://github.com/NixOS/nix/issues/7359. You could try setting the `nix_version` input of the CI workflow to `2.10.3` and see if it works.

Your second run, that is a bug in nixbuild.net. Sometimes when building a tree of derivations, the actual build failure is not visible, instead you only see the cancelled builds that was depending on the failed build. Sorry about this, we're working on fixing that. However, if you scroll back in your GitHub Actions [log](https://github.com/gvolpe/nix-config/actions/runs/4113703021/jobs/7100160609#step:6:6838), you can see that the actual error is the failed download of the `chatgpt_for_google-1.15.1.xpi` file that you then see again in the next run.

Speaking about that [download](https://addons.mozilla.org/firefox/downloads/file/4057649/chatgpt_for_google-1.15.1.xpi), I get a 404 too if I just try to fetch it with curl on my local machine. Maybe it changed upstream, but you managed to download a copy to your local Nix store earlier? If you have the store path on your local machine you can just push it to nixbuild.net using `nix-copy-closure` or `nix copy`.

I see that we should make a new release that includes the latest Nix versions, thank you for reminding me.

I did make a [change](https://github.com/nixbuild/nixbuild-action/commit/4ff3d0c03feff436d9ea44c90601a758b51baaaf) to enable the summary to be shown also on failures, but I now realize that change is probably not enough. I'll see if I can fix that.

**Comment by gvolpe** [comment]
> The Too many root sets issue is a client error that started to appear in Nix around version 2.11.1, see https://github.com/NixOS/nix/issues/7359. You could try setting the nix_version input of the CI workflow to 2.10.3 and see if it works.

Thanks for the info! Unfortunately, my Home Manager derivations need IFD, and the option `allow-import-from-derivation` doesn't seem to work with lower versions than 2.12.0, or perhaps it has a different name? 🤔 

> However, if you scroll back in your GitHub Actions [log](https://github.com/gvolpe/nix-config/actions/runs/4113703021/jobs/7100160609#step:6:6838), you can see that the actual error is the failed download of the chatgpt_for_google-1.15.1.xpi file that you then see again in the next run.

Ah that's my bad, sorry about that, it must have been cached! Indeed, this extension no longer exists for Firefox: https://chatgpt4google.com/

> I see that we should make a new release that includes the latest Nix versions, thank you for reminding me.
> I did make a [change](https://github.com/nixbuild/nixbuild-action/commit/4ff3d0c03feff436d9ea44c90601a758b51baaaf) to enable the summary to be shown also on failures, but I now realize that change is probably not enough. I'll see if I can fix that.

Thank you 💟 

---

Thanks to your help I got it working even with Nix 2.12.0, this is pretty neat! 🤩 

https://github.com/gvolpe/nix-config/actions/runs/4117105912

**Comment by gvolpe** [comment]
Follow-up question: are `nixosConfigurations` not supported? I added this but it seemed to get ignored.

```yaml
filter_builds: '.top_attr == "packages" or .top_attr == "nixosConfigurations"'
```

**Comment by rickynils** [comment]
@gvolpe You need to drill further down into the `nixosConfigurations` attributes in order to get something that is directly buildable. However, I have some flakes that just add the NixOS builds to `checks` like this:

```
      checks.x86_64-linux = nixpkgs.lib.mapAttrs 
         (_: c: c.config.system.build.toplevel) 
         self.nixosConfigurations;
```

This also makes the configs build when running `nix flake check`, which is convenient.

**Comment by gvolpe** [comment]
Got it 👍🏽 Similar to what I do for HM

```nix
{
  packages.${system} = {
    inherit (ci) metals metals-updater;
    home-edp = home.gvolpe-edp.activationPackage;
    home-hdmi = home.gvolpe-hdmi.activationPackage;
  };
}
```
