### ISSUE TITLE
Allow setting LFS on checkout

### ISSUE THREAD

**Issue by KaiserKarel** [nixbuild/nixbuild-action#39]
Currently git checkout in the recommended workflow does not allow setting `lfs: true` through inputs; which means users would need to copy paste the workflow.

**Comment by rickynils** [comment]
Fixed in https://github.com/nixbuild/nixbuild-action/pull/40

**Comment by rickynils** [comment]
Available in [v17](https://github.com/nixbuild/nixbuild-action/releases/tag/v17).
