### ISSUE TITLE
Setup failed when workflow name contains spaces

### ISSUE THREAD

**Issue by Julow** [nixbuild/nixbuild-action#9]
The step `nixbuild/nixbuild-action@v8` fails when the workflow name contains spaces (the `name` field at the toplevel of the file) with this error:

```
/etc/ssh/ssh_config line 61: Invalid SetEnv.
```

It generates a line looking like:

```
  SetEnv SOME_VARIABLE='My workflow name' OTHER_VARIABLES...
```
I'm not sure what's happening but the documentation for ssh_config only talks about double quotes (`"`).

**Comment by rickynils** [comment]
This was actually fixed just an hour ago, in [v9](https://github.com/nixbuild/nixbuild-action/releases/tag/v9). Can you try it and see if it works?

**Comment by rickynils** [comment]
Single quotes are actually supported in newer versions of OpenSSH, I guess that was the reason they were used. However, the version of OpenSSH installed in the GitHub runners only supports double quotes.

**Comment by Julow** [comment]
v9 is working, thanks!
